### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by norbornen** [norbornen/cyanic#8]
- [x]  add ExtSource.notification_channels
- [x]  в NotificationUsecase посылать уведомления по каналам указанным в ExtSource.notification_channels каждого Offer-а
- [x]  delete ExtSource.protocol
- [x]  add ExtSource.transport
- [x]  add ExtSource.factory
- [x] NotificationChannel: посмотреть можно ли типизировать connection по значению provider
- [ ]  добавить в Offer признак "деактивировано (снято)"
- [x]  add ExtSource.crontab
- [ ]  synchronization daemon (нужен вотчер на коллекцию extSource чтобы отслеживать появление записей и изменение is_active (приостанавливает обработку задач, если она есть))
